# Generated by Django 4.2.1 on 2023-05-24 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_education', models.CharField(choices=[('correspondence_abbreviated', 'Заочная сокращенная'), ('correspondence', 'Заочная'), ('full_time', 'Дневная')], default='full_time', max_length=40, verbose_name='Форма обучения')),
                ('course', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Курс (стадия обучения)')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('abbreviated_name', models.CharField(max_length=7, unique=True, verbose_name='Сокращенное название')),
                ('qualification', models.CharField(max_length=128, verbose_name='Квалификация')),
                ('study_period', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Период обучения')),
                ('admission_plan', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='План приема')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'специальности',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=24, verbose_name='Отчество')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.speciality', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='groups',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='main.subjects', verbose_name='Предметы'),
        ),
    ]
