# Generated by Django 4.2.1 on 2023-05-24 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Отметка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='main.students', verbose_name='Студен')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='main.subjects', verbose_name='Предмет')),
            ],
        ),
    ]
