# Generated by Django 4.1.7 on 2023-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_out', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingout',
            options={'verbose_name': 'отработка', 'verbose_name_plural': 'отработки'},
        ),
        migrations.AlterField(
            model_name='workingout',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
